apiVersion: apps/v1
kind: Deployment
metadata:
  name: hot-store
  namespace: quantatom-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hot-store
  template:
    metadata:
      labels:
        app: hot-store
    spec:
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: hot-store
  namespace: quantatom-system
spec:
  selector:
    app: hot-store
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
