apiVersion: apps/v1
kind: Deployment
metadata:
  name: warm-store
  namespace: quantatom-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: warm-store
  template:
    metadata:
      labels:
        app: warm-store
    spec:
      containers:
      - name: clickhouse
        image: clickhouse/clickhouse-server:latest
        ports:
        - containerPort: 8123
---
apiVersion: v1
kind: Service
metadata:
  name: warm-store
  namespace: quantatom-system
spec:
  selector:
    app: warm-store
  ports:
  - protocol: TCP
    port: 8123
    targetPort: 8123
